export const doorSys = '/doorSys'
export const fieldSys = '/fieldSys'
export const vehicleSys = '/vehicleSys'
export const dormitorySys = '/dormitorySys'
export const basicServer = '/basicServer'
export const estateServer = '/estateServer'
export const vehicleServer = '/vehicleServer'
export const paymentServer = '/payment'
